### ISSUE TITLE
Package brew not installed(Mac when I pay the VPN)

### ISSUE THREAD

**Issue by Ajrocwuu** [sentinel-official/sentinel#52] opened 2018-04-20 07:56 UTC

**Comment by riotcs** [comment] 2018-04-28 06:02
Can you explain the problem more clearly? Did you follow the setup guide throughout?

**Comment by Arsca** [comment] 2018-06-16 15:40
Hi,

Chiming in here as I have the same issue.

I have the same problem on my MacOS: 10.13.5 (17F77)
1) Activate the Testnet switch
2) Click to connect to one of the VPN points on the list
3) In the dialog, press connect to chosen VPN end point
4) Balck "Package Brew is not Installed" alert panel appear.

**Comment by fabulous345** [comment] 2018-08-23 05:12
Did you install homebrew according to the setup guide?

**Comment by tonyxia2016** [comment] 2018-10-08 09:08
Got the same issue here. Sentinel 0.0.5 alpha, MacOS 10.14.  
Always show "Package brew not installed" when I click a VPN. Homebrew installed, and upgraded to the latest version. What else do I need to do? Where is the install document for Mac?

**Comment by tonyxia2016** [comment] 2018-10-09 06:17
Follow the install help https://github.com/sentinel-official/sentinel/tree/master/wallet and install homebrew again https://www.howtogeek.com/211541/homebrew-for-os-x-easily-installs-desktop-apps-and-terminal-utilities/ , the issue is still there.    Sentinel 0.0.5 alpha, MacOS 10.14.

**Comment by ymai6** [comment] 2018-12-12 11:30
一样的问题

**Comment by thenikin** [comment] 2019-04-03 15:45
this is still happening to me. Latest mac os, homebrew installed. Any hints?

**Comment by octalmage** [comment] 2019-06-02 19:36
So I was having the same issue, and it was because I did not open the package like the instructions state and run the binary directly! After doing that, the homebrew error went away but then I got an error related to not being able to install OpenVPN. 

After this I decided to close everything, open the terminal and run Sentinel directly using sudo. This was the full command:

```
sudo /Applications/sentinel.app/Contents/MacOS/sentinel
```

After doing this everything is working as expected! 

![Screen Shot 2019-06-02 at 2 36 10 PM](https://user-images.githubusercontent.com/142006/58766408-c707f000-8543-11e9-93e8-fa1cae728df0.png)

I hope this helps! Great work so far on the app, looks fantastic!

**Comment by anthrax314** [comment] 2019-07-16 19:13
Thank You @tonyxia2016 & @octalmage for your answers. Closing this issue.

**Closed by anthrax314** 2019-07-16 19:13 UTC
